version: '3.3'
services:
  node:
    image: ${REGISTRY}/${STACK}:latest
    environment:
      - PORT=${PORT}
    networks:
      - traefik
    deploy:
      mode: replicated
      replicas: ${REPLICAS_NODE}
      restart_policy:
        condition: on-failure
      labels:
          - "traefik.backend=${STACK}_node"
          - "traefik.frontend.rule=Host:${URL}"
          - "traefik.port=${PORT}"
      placement:
        constraints:
          - engine.labels.class == application
networks:
  traefik:
    external:
      name: traefik-net
